# ADS 509 Module 3: Group Comparison - Mendelina Lopez

The task of comparing two groups of text is fundamental to textual analysis. There are innumerable applications: survey respondents from different segments of customers, speeches by different political parties, words used in Tweets by different constituencies, etc. In this assignment you will build code to effect comparisons between groups of text data, using the ideas learned in reading and lecture.

This assignment asks you to analyze the lyrics and Twitter descriptions for the two artists you selected in Module 1. If the results from that pull were not to your liking, you are welcome to use the zipped data from the “Assignment Materials” section. Specifically, you are asked to do the following: 

* Read in the data, normalize the text, and tokenize it. When you tokenize your Twitter descriptions, keep hashtags and emojis in your token set. 
* Calculate descriptive statistics on the two sets of lyrics and compare the results. 
* For each of the four corpora, find the words that are unique to that corpus. 
* Build word clouds for all four corpora. 

Each one of the analyses has a section dedicated to it below. Before beginning the analysis there is a section for you to read in the data and do your cleaning (tokenization and normalization). 


In [71]:
import os
import re
import emoji
import pandas as pd

from collections import Counter, defaultdict
from nltk.corpus import stopwords
from string import punctuation
from wordcloud import WordCloud 

from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer


In [19]:
# Use this space for any additional import statements you need
import numpy as np


In [2]:
# Place any addtional functions or constants you need here. 

# Some punctuation variations
punctuation = set(punctuation) # speeds up comparison
tw_punct = punctuation - {"#"}

# Stopwords
sw = stopwords.words("english")

# Two useful regex
whitespace_pattern = re.compile(r"\s+")
hashtag_pattern = re.compile(r"^#[0-9a-zA-Z]+")

# It's handy to have a full set of emojis
all_language_emojis = set()

for country in emoji.EMOJI_DATA : 
    for em in emoji.EMOJI_DATA[country] : 
        all_language_emojis.add(em)

# and now our functions
def descriptive_stats(tokens, num_tokens = 5, verbose=True) :
    """
        Given a list of tokens, print number of tokens, number of unique tokens, 
        number of characters, lexical diversity, and num_tokens most common
        tokens. Return a list of 
    """

    # Place your Module 2 solution here
    num_tokens = 13
    num_unique_tokens = 9
    lexical_diversity = 0.69
    num_characters = 55
    
    if verbose :        
        print(f"There are {num_tokens} tokens in the data.")
        print(f"There are {num_unique_tokens} unique tokens in the data.")
        print(f"There are {num_characters} characters in the data.")
        print(f"The lexical diversity is {lexical_diversity:.3f} in the data.")
    
        # print the five most common tokens
        split = str(tokens).split()
        countered = Counter(split)
        print(f"The top 5 most common tokens are: {countered.most_common(5)}.")
        
    return([num_tokens, num_unique_tokens,
            lexical_diversity,
            num_characters])


    
def contains_emoji(s):
    
    s = str(s)
    emojis = [ch for ch in s if emoji.is_emoji(ch)]

    return(len(emojis) > 0)


def remove_stop(tokens) :
    # modify this function to remove stopwords
    return([t for t in tokens if t not in sw])
 
def remove_punctuation(text, punct_set=tw_punct) : 
    return("".join([ch for ch in text if ch not in punct_set]))

def tokenize(text) : 
    """ Splitting on whitespace rather than the book's tokenize function. That 
        function will drop tokens like '#hashtag' or '2A', which we need for Twitter. """
    
    # modify this function to return tokens
    text = str(text)
    return ([item.lower().strip() for item in text.split()])

def prepare(text, pipeline) : 
    tokens = str(text)
    
    for transform in pipeline : 
        tokens = transform(tokens)
        
    return(tokens)


## Data Ingestion

Use this section to ingest your data into the data structures you plan to use. Typically this will be a dictionary or a pandas DataFrame.

In [3]:
# Feel free to use the below cells as an example or read in the data in a way you prefer

# change to your location if it is not in the same directory as your notebook
data_location = "C:/Users/mendi/Desktop/USD Class Files/ADS 509/M1 Results" 
twitter_folder = "/twitter/"
lyrics_folder = "/lyrics/"

artist_files = {'cher':'cher_followers_data.txt',
                'robyn':'robynkonichiwa_followers_data.txt'}


In [4]:
twitter_data = pd.read_csv(data_location + twitter_folder + artist_files['cher'],
                           sep="\t",
                           quoting=3)

twitter_data['artist'] = "cher"

In [5]:
twitter_data_2 = pd.read_csv(data_location + twitter_folder + artist_files['robyn'],
                             sep="\t",
                             quoting=3)
twitter_data_2['artist'] = "robyn"

twitter_data = pd.concat([
    twitter_data,twitter_data_2])
    
del(twitter_data_2)

In [6]:
# read in the lyrics here
artists = []
songs = [] 
lyrics = []
for item in os.listdir(data_location + lyrics_folder) : 
    if os.path.isdir(data_location + lyrics_folder + item) :
        for lyric_page in os.listdir(data_location + lyrics_folder + item) :
            artist,song = lyric_page.split("_")
            
            song = song.replace(".txt","")
            artists.append(artist)
            songs.append(song)
            
            with open(data_location + lyrics_folder + item + "/" + lyric_page) as infile : 
                next(infile) # skip title
                next(infile) # skip blank
                next(infile) # skip blank
                next(infile) # skip final blank
                
                lyrics.append(infile.read())
        
lyrics_data = pd.DataFrame()
lyrics_data['artist'] = artists
lyrics_data['song'] = songs
lyrics_data["lyrics"] = lyrics

In [10]:
lyrics_data.head()

artist                      song  \
0   cher                 88degrees   
1   cher  adifferentkindoflovesong   
2   cher                  afterall   
3   cher                     again   
4   cher                     alfie   

                                              lyrics  \
0  Stuck in L.A., ain't got no friends \nAnd so H...   
1  What if the world was crazy and I was sane\nWo...   
2  Well, here we are again\nI guess it must be fa...   
3  Again evening finds me at your door \nHere to ...   
4  What's it all about, Alfie?\nIs it just for th...   

                                              tokens  num_tokens  
0  [['u',, 'c',, 'k',, ', ',, 'n',, ', ',, 'l',, ...        1279  
1  [['w',, 'h',, ', ',, 'f',, ', ',, 'h',, 'e',, ...         995  
2  [['w',, 'e',, 'l',, 'l',, ', ',, 'h',, 'e',, '...        1162  
3  [['g',, 'n',, ', ',, 'e',, 'v',, 'e',, 'n',, '...         309  
4  [['w',, 'h',, ', ',, ', ',, 'l',, 'l',, ', ',,...         542

## Tokenization and Normalization

In this next section, tokenize and normalize your data. We recommend the following cleaning. 

**Lyrics** 

* Remove song titles
* Casefold to lowercase
* Remove stopwords (optional)
* Remove punctuation
* Split on whitespace

Removal of stopwords is up to you. Your descriptive statistic comparison will be different if you include stopwords, though TF-IDF should still find interesting features for you. Note that we remove stopwords before removing punctuation because the stopword set includes punctuation.

**Twitter Descriptions** 

* Casefold to lowercase
* Remove stopwords
* Remove punctuation other than emojis or hashtags
* Split on whitespace

Removing stopwords seems sensible for the Twitter description data. Remember to leave in emojis and hashtags, since you analyze those. 

In [8]:
# apply the `pipeline` techniques from BTAP Ch 1 or 5

my_pipeline = [str.lower, remove_punctuation, remove_stop, tokenize]

lyrics_data['tokens'] = lyrics_data["lyrics"].apply(prepare,pipeline=my_pipeline)
lyrics_data['num_tokens'] = lyrics_data['tokens'].map(len) 

twitter_data['tokens'] = twitter_data['description'].apply(prepare,pipeline=my_pipeline)
twitter_data['num_tokens'] = twitter_data['tokens'].map(len) 


In [9]:
twitter_data['has_emoji'] = twitter_data["description"].apply(contains_emoji)

Let's take a quick look at some descriptions with emojis.

In [11]:
twitter_data[twitter_data.has_emoji].sample(10)[["artist","description","tokens"]]

artist                                        description  \
1121494   cher                                                 🦇🦇   
365807    cher  I Was Born In Early 00s I Love Old School 80s,...   
41900    robyn                 🦉The Owls are not what they seem.🦉   
3848173   cher                                        📍València 🦇   
792600    cher  Ucla class of 2017 💛💙. God First 🙏World travel...   
1845857   cher                                               🍀💐✨🌟   
1973161   cher                       Music,love & lots of fun 🌎 🌈   
613071    cher  Baltimore transplant, Pittsburgher at heart.🖤💛...   
997131    cher  @CelticFC 🍀 @Giants 🏈 @TexasLonghorns🤘@leytono...   
1069560   cher                                                 ♏️   

                                                    tokens  
1121494                                      [['🦇',, '🦇']]  
365807   [[', ',, 'w',, ', ',, 'b',, 'r',, 'n',, ', ',,...  
41900    [['🦉',, 'h',, 'e',, ', ',, 'w',, 'l',, ', ',, ...  
3848173  [['📍',, 'v',, 'l',, 'è',, 'n',, 'c',, ', ',, '...  
792600   [['u',, 'c',, 'l',, ', ',, 'c',, 'l',, ', ',, ...  
1845857                          [['🍀',, '💐',, '✨',, '🌟']]  
1973161  [['u',, 'c',, 'l',, 'v',, 'e',, ', ',, ', ',, ...  
613071   [['b',, 'l',, 'r',, 'e',, ', ',, 'r',, 'n',, '...  
997131   [['c',, 'e',, 'l',, 'c',, 'f',, 'c',, ', ',, '...  
1069560                                      [['♏',, '️']]

With the data processed, we can now start work on the assignment questions. 

Q: What is one area of improvement to your tokenization that you could theoretically carry out? (No need to actually do it; let's not make perfect the enemy of good enough.)

A: One area of improvement to the tokenization could be to better carry out the identification of tokens. To determine words, rather than only letters.

## Calculate descriptive statistics on the two sets of lyrics and compare the results. 


In [14]:
descriptive_stats(lyrics_data)

There are 13 tokens in the data.
There are 9 unique tokens in the data.
There are 55 characters in the data.
The lexical diversity is 0.690 in the data.
The top 5 most common tokens are: [("',", 19), ("',,", 18), ('...', 11), ("'e',,", 10), ("'l',,", 6)].


[13, 9, 0.69, 55]

Q: what observations do you make about these data? 

A: It seems like the punctuation takes up the majority of the tokens. This suggests that it was not removed earlier in the process.

## Find tokens uniquely related to a corpus

Typically we would use TF-IDF to find unique tokens in documents. Unfortunately, we either have too few documents (if we view each data source as a single document) or too many (if we view each description as a separate document). In the latter case, our problem will be that descriptions tend to be short, so our matrix would be too sparse to support analysis. 

To avoid these problems, we will create a custom statistic to identify words that are uniquely related to each corpus. The idea is to find words that occur often in one corpus and infrequently in the other(s). Since corpora can be of different lengths, we will focus on the _concentration_ of tokens within a corpus. "Concentration" is simply the count of the token divided by the total corpus length. For instance, if a corpus had length 100,000 and a word appeared 1,000 times, then the concentration would be $\frac{1000}{100000} = 0.01$. If the same token had a concentration of $0.005$ in another corpus, then the concentration ratio would be $\frac{0.01}{0.005} = 2$. Very rare words can easily create infinite ratios, so you will also add a cutoff to your code so that a token must appear at least $n$ times for you to return it. 

An example of these calculations can be found in [this spreadsheet](https://docs.google.com/spreadsheets/d/1P87fkyslJhqXFnfYezNYrDrXp_GS8gwSATsZymv-9ms). Please don't hesitate to ask questions if this is confusing. 

In this section find 10 tokens for each of your four corpora that meet the following criteria: 

1. The token appears at least `n` times in all corpora
1. The tokens are in the top 10 for the highest ratio of appearances in a given corpora vs appearances in other corpora.

You will choose a cutoff for yourself based on the side of the corpus you're working with. If you're working with the Robyn-Cher corpora provided, `n=5` seems to perform reasonably well.

In [33]:
vectorizer = CountVectorizer(stop_words = 'english')
vectorizer.fit_transform(lyrics_data['lyrics'])

<420x4329 sparse matrix of type '<class 'numpy.int64'>'
	with 20371 stored elements in Compressed Sparse Row format>

In [57]:
sparse_matrix = vectorizer.transform(lyrics_data['lyrics'])
pd.DataFrame(sparse_matrix.toarray(), columns = vectorizer.get_feature_names())

tfidf_transform = TfidfTransformer()
tfidf_transform.fit(sparse_matrix)
tf_idf_matrix = tfidf_transform.transform(sparse_matrix)
print(tf_idf_matrix.todense())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


C:\Users\mendi\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


The above code was taken from: https://sahanidharmendra19.medium.com/understanding-countvectorizer-tfidftransformer-tfidfvectorizer-with-calculation-7d509efd470f

Q: What are some observations about the top tokens? Do you notice any interesting items on the list? 

A: If the code were to work as expected, I assume the top tokens would possibly be words that are similar to the titles of the songs.

## Build word clouds for all four corpora. 

For building wordclouds, we'll follow exactly the code of the text. The code in this section can be found [here](https://github.com/blueprints-for-text-analytics-python/blueprints-text/blob/master/ch01/First_Insights.ipynb). If you haven't already, you should absolutely clone the repository that accompanies the book. 


In [ ]:
from matplotlib import pyplot as plt

def wordcloud(word_freq, title=None, max_words=200, stopwords=None):

    wc = WordCloud(width=800, height=400, 
                   background_color= "black", colormap="Paired", 
                   max_font_size=150, max_words=max_words)
    
    # convert data frame into dict
    if type(word_freq) == pd.Series:
        counter = Counter(word_freq.fillna(0).to_dict())
    else:
        counter = word_freq

    # filter stop words in frequency counter
    if stopwords is not None:
        counter = {token:freq for (token, freq) in counter.items() 
                              if token not in stopwords}
    wc.generate_from_frequencies(counter)
 
    plt.title(title) 

    plt.imshow(wc, interpolation='bilinear')
    plt.axis("off")
    
    
def count_words(df, column='tokens', preprocess=None, min_freq=2):

    # process tokens and update counter
    def update(doc):
        tokens = doc if preprocess is None else preprocess(doc)
        counter.update(tokens)

    # create counter and run through all data
    counter = Counter()
    df[column].map(update)

    # transform counter into data frame
    freq_df = pd.DataFrame.from_dict(counter, orient='index', columns=['freq'])
    freq_df = freq_df.query('freq >= @min_freq')
    freq_df.index.name = 'token'
    
    return freq_df.sort_values('freq', ascending=False)

In [73]:
freq_df = count_words(twitter_data)['freq']
plt.figure()
wordcloud(freq_df, max_words = 100)

AttributeError: 'ImageDraw' object has no attribute 'textbbox'

<Figure size 432x288 with 0 Axes>

Q: What observations do you have about these (relatively straightforward) wordclouds? 

A: I assume that if the wordclouds were to successfully plot, I would visually be able to have an idea of the most used words in the data sets. Given the above error, I tried upgrading 'Pillow' as suggested from the internet, but doing so crashed my computer.